### ISSUE TITLE
Eq constraint on Abstr essential?

### ISSUE THREAD

**Issue by ggreif** [eelco/gdiff#4]
I am wondering what the necessity of the `Eq` constraint on `Abstr :: (Eq t, List f ts)  => (t ->  f t ts)  -> Con f t` is...

I managed to compile `gdiff` without it, so I do not think it is needed from the algorithm side of things. From the user's perspective it weakens the theory by adding a constraint that (e.g.) the Family GADT could require instead. In my fork I'll gather some experience and then submit a PR.

**Comment by eelco** [comment]
(I’ve not touched this code in a very long time, in fact, I had to read a bit in my own thesis to load everything in, and I have not tried to compile anything, so I might be completely wrong, but…)

I’d expect is necessary since for implementing the family instance since for diffing you’d also need to compare the actual values inside the abstract type (see the `decEq` pattern matching in the implementation example).

**Comment by ggreif** [comment]
Hi @eelco , nice to hear from you! It is correct that for `Abstr` constructors one has to perform a comparison, but that does not mean it has to happen by means of the `Eq` methods. See:
``` haskell
class Family MyFam where
  Bool' True `decEq` Bool' True = return (Refl, Refl) -- by pattern matching
  Foo' f1 `decEq` Foo' f2 | f1 == f2 = return (Refl, Refl) -- by Eq constraint from Foo'
  l@Nat' `decEq` r@Nat' = do Refl <- l `sameNat` r; return (Refl, Refl) -- by type-level reasoning (KnownNat constraint)
```
None of these needs the `Eq` constraint _from `Abstr`_. Actually an `Eq` constraint might not exist at all! I use `Abstr` routinely, e.g. for types with existentially abstracted types. If you want I can come up with a more elaborate example.

**Comment by eelco** [comment]
Oh, that’s a great point. Well, I guess it can be removed then, if you don’t find any other issues. Looking forward to your pull request ;)
